# Generated by Django 5.1.2 on 2024-11-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('position', models.CharField(max_length=50, verbose_name='Позиция')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Рост (см)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
    ]
