# Generated by Django 5.1.2 on 2024-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
