# Generated by Django 5.1.2 on 2024-11-12 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='player',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
